VS-5 section-two images
KapsarovR/vue-sample pull request #5
Opened 2022-09-28 15:35 UTC by KapsarovR

2022-09-30 02:58 UTC, SchnapsterDog requested changes
Воглавно е супер. Неколку измени плус.

Во cube класата, посоодветно би било сликата (image) да ти е со position absolute, а cube-title и cube-description relative. Така ќе можеш во парентот .cube да имаш флексбокс и да ги сетираш елементите според тоа. Многу полесно би било и почист кодот би бил.

Тоа што го имаш во цсс за cube-title position: absolute, top: 0, left: 50, transform: ... ќе ги избришеш. Исто и во cube-second или по ново cube-description класата.

2022-09-30 02:58 UTC, SchnapsterDog commented on src/App.vue
> +          <h2>Paragraph</h2>
Наместо Paragraph, стави си како текст Title

2022-09-30 02:58 UTC, SchnapsterDog commented on src/App.vue
> +        <div class="cube-second">
Посоодветно име за класа би било cube-description. Смени и во цсс истото :)

2022-09-30 02:58 UTC, SchnapsterDog commented on src/App.vue
> +        <div class="cube-second">
Посоодветно име за класа би било cube-description

2022-09-30 02:58 UTC, SchnapsterDog commented on src/App.vue
> +        <div class="cube-second">
Посоодветно име за класа би било cube-description

2022-09-30 02:58 UTC, SchnapsterDog commented on src/App.vue
> +.cube-second {
Пошто и горе ќе ја промениш класата и тука ќе треба да ја промениш.

2022-09-30 02:59 UTC, SchnapsterDog commented on src/App.vue
> +  position: absolute;
Тука ќе ги избришеш сите овие работи што ги имаш освен color, пошто релативна ќе ти оваа класа.

2022-09-30 03:00 UTC, SchnapsterDog commented on src/App.vue
> +  position: absolute;
Исто и тука, сите овие работи што се однесуваат на absolute ќе ги тргнеш. Само бојата и фонтот нека останат.

2022-09-30 03:01 UTC, SchnapsterDog commented on src/App.vue
> +  position: relative;
Ова можеме да го направиме со position absolute, width: 100%, height: 100% top: 0, left: 0. Само на парентот ќе мораш да имаш position: relative.

2022-09-30 15:32 UTC, KapsarovR commented on src/App.vue
> +  position: relative;
Nemozam da ja razberam poentata za promenata

2022-09-30 18:04 UTC, SchnapsterDog commented on src/App.vue
> +  position: relative;
Поентата е тоа што парентот ќе го направиме со флексбокс наместо  два засебни елементи да имаат position: absolute, transform, left и топ. Многу поедноставен ќе ни е кодот. Само сликата би требало според мене да има position: absolute, другото не. И парентот треба да има flex.

2022-09-30 18:06 UTC, SchnapsterDog commented on src/App.vue
> +  position: relative;
Плус ова не е едноставно за читање. Можеби би можело да се користи каде што не би можел флексбокс, ама за вака поедноставни работи, не би требало според мене.

left: 50%;
transform: translate(-50%, 0);

2022-10-02 19:05 UTC, KapsarovR commented on src/App.vue
> +  position: relative;
Imam napraveno izmeni probav da gi pushtam i git ne mi dade ke ostavam taka utre ke vidime shto i kade zgreshiv . Prijatna vecher

2022-10-03 16:34 UTC, SchnapsterDog approved these changes
Good job!

2022-10-03 16:34 UTC, merged