VS-9 AppSection config
KapsarovR/vue-sample pull request #9
Opened 2022-10-21 13:52 UTC by KapsarovR

2022-10-26 12:33 UTC, SchnapsterDog commented on src/components/AppImages.vue
> +      <img class="image" :src="item.images" alt="" {{ images }} />
Тука ти е грешката. Ти имаш :src="item.images". Ама никаде во кодот немаш во компонентата item.images. Треба да ти биде само :src="image" 

Исто тоа во {{ images }} избриши го, не постои ваква конструкција :)

2022-10-26 12:34 UTC, SchnapsterDog commented on src/components/AppImages.vue
> +  props: ["images"]
Тука нека ти е во еднина "image" наместо во множина "images". Компонентава треба да прими податок само една слика.

2022-10-26 12:35 UTC, SchnapsterDog commented on src/components/AppSectionFour.vue
> +      <!-- <app-images :src="item.images"/> -->
Исто преименувај ја компонентата во еднина. <app-image> наместо <app-images> 

Ќе треба и таму каде што ја повикуваш и секаде ја преименуваш за да биде појасно

2022-10-26 12:38 UTC, SchnapsterDog commented on src/components/AppSectionTwo.vue
> +      <img :src="item.images" class="images" alt="" />
Исто и тика можеш да ја додадеш компонентата за сликата.

2022-10-26 12:38 UTC, SchnapsterDog requested changes
Ѕирни ги сугестииве, измени во кодот и може да мерџниме :)

2022-10-26 17:02 UTC, KapsarovR commented on src/components/AppSectionTwo.vue
> +      <img :src="item.images" class="images" alt="" />
Gi napraviv site izmeni no slikite povtorno ne mi se pojavija neznam zoshto :(

2022-10-31 17:30 UTC, SchnapsterDog approved these changes
Good job!

2022-10-31 17:30 UTC, merged